# Generated by Django 2.0.2 on 2018-02-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraftScapeDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype_static',
            name='game_item_id',
        ),
    ]
