# Generated by Django 2.0.2 on 2018-02-23 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=255)),
                ('health', models.FloatField()),
                ('max_health', models.FloatField()),
                ('currency', models.IntegerField()),
                ('walk_speed', models.FloatField()),
                ('max_inventories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Character_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.Character')),
            ],
        ),
        migrations.CreateModel(
            name='GameItem_static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('max_stack', models.IntegerField()),
                ('value', models.FloatField()),
                ('rarity', models.IntegerField(choices=[(1, 'Common'), (2, 'Rare'), (3, 'Legendary')], default=1)),
                ('min_level', models.IntegerField()),
                ('base_durability', models.IntegerField()),
                ('soulbound', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_size', models.IntegerField()),
                ('inventory_type', models.CharField(choices=[('DE', 'default'), ('SB', 'smallBag'), ('MB', 'mediumBag'), ('LB', 'largeBag')], default='DE', max_length=2)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_GameItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crafted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CraftScapeDatabase.Character')),
                ('game_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.GameItem_static')),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryGameItem_ItemModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_game_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.Inventory_GameItem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_remainder', models.IntegerField()),
                ('modifier_remainder', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemModifier_can_effect_ItemType_static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModifier_static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('modifier', models.FloatField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemType_static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=30)),
                ('game_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.GameItem_static')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('skill_type', models.CharField(max_length=30)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill_SkillDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('U', 'union'), ('I', 'intersection')], default='U', max_length=1)),
                ('child_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childSkill', to='CraftScapeDatabase.Skill')),
                ('parent_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentSkill', to='CraftScapeDatabase.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='itemmodifier_can_effect_itemtype_static',
            name='item_modifier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.ItemModifier_static'),
        ),
        migrations.AddField(
            model_name='itemmodifier_can_effect_itemtype_static',
            name='item_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.ItemType_static'),
        ),
        migrations.AddField(
            model_name='itemmodifier',
            name='item_modifier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.ItemModifier_static'),
        ),
        migrations.AddField(
            model_name='inventorygameitem_itemmodifier',
            name='inventory_modifier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.ItemModifier'),
        ),
        migrations.AddField(
            model_name='gameitem_static',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemType', to='CraftScapeDatabase.ItemType_static'),
        ),
        migrations.AddField(
            model_name='character_skill',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.Skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory_1_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory1', to='CraftScapeDatabase.Inventory'),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory_2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory2', to='CraftScapeDatabase.Inventory'),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory_3_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory3', to='CraftScapeDatabase.Inventory'),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory_4_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory4', to='CraftScapeDatabase.Inventory'),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory_5_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory5', to='CraftScapeDatabase.Inventory'),
        ),
        migrations.AddField(
            model_name='character',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.User'),
        ),
    ]
