# Generated by Django 2.0.3 on 2018-04-03 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('health', models.FloatField(default=100)),
                ('max_health', models.FloatField(default=100)),
                ('currency', models.IntegerField(default=0)),
                ('walk_speed', models.FloatField(default=10)),
                ('max_inventories', models.IntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'character',
            },
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.Character')),
            ],
            options={
                'db_table': 'character_skill',
            },
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_position', models.IntegerField()),
                ('stack_size', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to='CraftScapeDatabase.Character')),
            ],
            options={
                'db_table': 'game_item',
            },
        ),
        migrations.CreateModel(
            name='GameItemModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.GameItem')),
            ],
            options={
                'db_table': 'game_item__item_modifier',
            },
        ),
        migrations.CreateModel(
            name='GameItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'game_item_type',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=-1)),
                ('size', models.IntegerField(default=8)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='CraftScapeDatabase.Character')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='ItemModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_remainder', models.IntegerField()),
                ('modifier_remainder', models.FloatField()),
            ],
            options={
                'db_table': 'item_modifier',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('skill_type', models.CharField(max_length=30)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='SkillDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('U', 'union'), ('I', 'intersection')], default='U', max_length=1)),
                ('child_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childSkill', to='CraftScapeDatabase.Skill')),
                ('parent_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentSkill', to='CraftScapeDatabase.Skill')),
            ],
            options={
                'db_table': 'skill_dependency',
            },
        ),
        migrations.CreateModel(
            name='StaticGameItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sprite_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('max_stack', models.IntegerField()),
                ('value', models.FloatField()),
                ('equipable', models.BooleanField()),
                ('rarity', models.IntegerField(choices=[(1, 'Common'), (2, 'Rare'), (3, 'Legendary')], default=1)),
                ('min_level', models.IntegerField()),
                ('base_durability', models.IntegerField()),
                ('soulbound', models.BooleanField(default=False)),
                ('power', models.FloatField(default=0)),
                ('defense', models.FloatField(default=0)),
                ('vitality', models.FloatField(default=0)),
                ('heal_amount', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'static_game_item',
            },
        ),
        migrations.CreateModel(
            name='StaticItemModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('modifier', models.FloatField()),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'item_modifier_static',
            },
        ),
        migrations.CreateModel(
            name='StaticItemTypeModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_modifier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.StaticItemModifier')),
                ('item_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.StaticGameItem')),
            ],
            options={
                'db_table': 'static_item_type_modifier',
            },
        ),
        migrations.AddField(
            model_name='itemmodifier',
            name='item_modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.StaticItemModifier'),
        ),
        migrations.AddField(
            model_name='gameitemtype',
            name='static_game_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_type', to='CraftScapeDatabase.StaticGameItem'),
        ),
        migrations.AddField(
            model_name='gameitemmodifier',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.ItemModifier'),
        ),
        migrations.AddField(
            model_name='gameitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_items', to='CraftScapeDatabase.Inventory'),
        ),
        migrations.AddField(
            model_name='gameitem',
            name='static_game_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_game_item', to='CraftScapeDatabase.StaticGameItem'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.Skill'),
        ),
    ]
