# Generated by Django 2.0.3 on 2018-04-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CraftScapeDatabase', '0003_skill_static_game_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back', to='CraftScapeDatabase.GameItem')),
                ('chest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest', to='CraftScapeDatabase.GameItem')),
                ('feet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feet', to='CraftScapeDatabase.GameItem')),
                ('hands', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='CraftScapeDatabase.GameItem')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head', to='CraftScapeDatabase.GameItem')),
                ('legs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='CraftScapeDatabase.GameItem')),
                ('neck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neck', to='CraftScapeDatabase.GameItem')),
                ('ring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ring', to='CraftScapeDatabase.GameItem')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='CraftScapeDatabase.GameItem')),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='CraftScapeDatabase.Equipment'),
        ),
    ]
