# Generated by Django 2.0.3 on 2018-04-13 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CraftScapeDatabase', '0004_auto_20180412_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='weapon',
        ),
        migrations.AddField(
            model_name='equipment',
            name='main_hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_hand', to='CraftScapeDatabase.GameItem'),
        ),
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='CraftScapeDatabase.Equipment'),
        ),
    ]
