# Generated by Django 2.0.3 on 2018-04-13 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CraftScapeDatabase', '0005_auto_20180412_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_items', to='CraftScapeDatabase.Inventory'),
        ),
    ]
