# Generated by Django 2.0.3 on 2018-04-14 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraftScapeDatabase', '0006_auto_20180412_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameitemtype',
            name='static_game_item',
        ),
    ]
