# Generated by Django 2.0.3 on 2018-04-14 17:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CraftScapeDatabase', '0008_staticgameitem_item_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back', to='CraftScapeDatabase.GameItem'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='chest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chest', to='CraftScapeDatabase.GameItem'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='feet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feet', to='CraftScapeDatabase.GameItem'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hands', to='CraftScapeDatabase.GameItem'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head', to='CraftScapeDatabase.GameItem'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='legs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs', to='CraftScapeDatabase.GameItem'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='main_hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_hand', to='CraftScapeDatabase.GameItem'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='neck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neck', to='CraftScapeDatabase.GameItem'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ring', to='CraftScapeDatabase.GameItem'),
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_items', to='CraftScapeDatabase.Inventory'),
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='static_game_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='static_game_item', to='CraftScapeDatabase.StaticGameItem'),
        ),
    ]
