# Generated by Django 2.0.3 on 2018-04-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CraftScapeDatabase', '0009_auto_20180414_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='shoulders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoulders', to='CraftScapeDatabase.GameItem'),
        ),
    ]
