# Generated by Django 2.0.3 on 2018-04-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CraftScapeDatabase', '0010_equipment_shoulders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='value',
            new_name='exp_cost',
        ),
        migrations.AddField(
            model_name='skill',
            name='exp_reward',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='CraftScapeDatabase.Skill'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='static_game_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CraftScapeDatabase.StaticGameItem'),
        ),
    ]
