# Generated by Django 2.0.3 on 2018-04-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraftScapeDatabase', '0011_auto_20180421_1401'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredient',
        ),
    ]
