# Generated by Django 2.0.3 on 2018-04-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraftScapeDatabase', '0012_auto_20180421_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
    ]
