# Generated by Django 2.0.3 on 2018-04-21 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CraftScapeDatabase', '0013_remove_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterskill',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='CraftScapeDatabase.Character'),
        ),
    ]
