# Generated by Django 2.0.3 on 2018-04-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftScapeDatabase', '0014_auto_20180421_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
