# Generated by Django 2.0.3 on 2018-04-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraftScapeDatabase', '0011_auto_20180423_1536'),
        ('CraftScapeDatabase', '0015_character_experience'),
    ]

    operations = [
    ]
